spring.application.name=Chapter12

spring.datasource.url=jdbc:postgresql://localhost:5432/Chapter13
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always

#custom.datasource.url=jdbc:postgresql://localhost:5432/postgres
#
#custom.datasource.username=postgres
#custom.datasource.password=postgres
